- hosts: centrifugo
  gather_facts: yes

  vars_files:
     - ./centrifugo_vars.yml

  tasks:
  - name: 'Download centrifugo repository installer'
    get_url: url=https://packagecloud.io/install/repositories/FZambia/centrifugo/script.rpm.sh dest=/tmp/script.rpm.sh

  - name: 'Changing perm of "/tmp/script.rpm.sh", adding "+x"'
    file: dest=/tmp/script.rpm.sh mode=a+x

  - name: 'Execute the script.rpm.sh' 
    shell: /tmp/script.rpm.sh
    become: yes

  - name: 'Remove the zsh-installer.sh'
    file: path=/tmp/script.rpm.sh state=absent

  - name: Checking for journald.conf
    become: yes
    stat: path=/etc/systemd/journald.conf
    register: journald_conf_file

  - name: Update journald setup
    become: yes
    replace:
      dest: /etc/systemd/journald.conf
      regexp: '^(\#| )?{{ item.var }}=\s*.*?$'
      replace: ' {{ item.var }}={{ item.val }}'
      backup: yes
    with_items: "{{ journald_vars_to_replace | default([]) }}"
    when: journald_conf_file.stat.exists
    register: journald_update

  # I need to restart journald immediatelly, otherwise it gets into way during
  # further steps in ansible
  - name: Restart journald
    become: yes
    systemd:
      name: systemd-journald
      state: restarted
    when: journald_update | changed

  - name: 'Install centrifugo package'
    become: yes
    yum:
      name: centrifugo
      state: latest
  
  - name: 'Copy centrifugo config'
    become: yes
    copy:
      src: "{{ centrifugo_config_src }}" 
      dest: /etc/centrifugo/config.json
      owner: centrifugo
      group: centrifugo

  - name: 'Make sure Centrifugo is running'
    become: yes
    systemd:
      state: started
      name: centrifugo 
