- hosts: all
  become: true
  tasks:
    - name: configure system settings, file descriptors and number of threads
      pam_limits:
        domain: sport24 
        limit_type: "{{item.limit_type}}"
        limit_item: "{{item.limit_item}}"
        value: "{{item.value}}"
      with_items:
        - { limit_type: '-', limit_item: 'nofile', value: 65536 }
        - { limit_type: '-', limit_item: 'nproc', value: 65536 }
        - { limit_type: 'soft', limit_item: 'memlock', value: unlimited }
        - { limit_type: 'hard', limit_item: 'memlock', value: unlimited }
    - name: reload settings from all system configuration files
      shell: sysctl --system

